resume= input('RESUME')
a=input('What is your name:')
b=input('Where do you reside:')
c=input('Sex:')
d=input('Date of Birth:')
e=input('Marital Status:')
f=input('Religion:')
g=input('Height:')
h=input('State of Origin:')
i=input('Local Govt Area:')
j=input('Phone Number:')
k=input('email address:')
l=input('Educational Background:')
m=input('Work History:')
n=input('Hobbies:')
o=input('Referees:')
    
